apiVersion: v2
name: vpa-creator
description: A controller that creates Vertical Pod Autoscalers for Deployments, StatefulSets, and DaemonSets.
type: application
version: 0.3.0
appVersion: 0.3.0
home: https://github.com/cloudoutloud/vpa-creator
sources:
  - https://github.com/cloudoutloud/vpa-creator
