nameOverride: ""
fullnameOverride: ""

namespace:
  create: true
  name: vpa-creator-system

replicaCount: 1

image:
  repository: "ghcr.io/cornfeedhobo/vpa-creator"
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true
  metricsAuth:
    create: true
  metricsReader:
    create: true

leaderElection:
  enabled: true

healthProbeBindAddress: ":8081"

vpa:
  enabled:
    deployments: true
    statefulsets: true
    daemonsets: true
  controlledValues: "RequestsAndLimits"

metrics:
  enabled: true
  secure: true
  bindAddress: ":8443"
  certificates:
    enabled: false
    secretName: metrics-server-cert
    mountPath: /tmp/k8s-metrics-server/metrics-certs
    certName: tls.crt
    certKey: tls.key
  service:
    port: 8443
    targetPort: 8443

serviceMonitor:
  enabled: false
  labels: {}
  interval: ""
  scrapeTimeout: ""
  tlsConfig:
    insecureSkipVerify: true
  certManager:
    enabled: false

enableHTTP2: false

networkPolicy:
  enabled: false
  namespaceSelector:
    matchLabels:
      metrics: enabled

podAnnotations:
  kubectl.kubernetes.io/default-container: controller

podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

terminationGracePeriodSeconds: 10
